### PR TITLE
feat: Want to Make Clap/Like count functional in Article page #295

### LINKED ISSUE #295: feat: Want to Make Clap/Like count functional in Article page
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently Like Functionality is not working in Article section I will make it work

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

Added Functionality to like and unlike Article in both ArticleHomepage and Single Articlespage

#295 

Fixes #295 
**Snapshots/Videos:**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/982aa6c6-9e35-4afc-b7f3-66a3b7eac4cf

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Doraemon012 @Tanay-ErrorCode Please review this pr and let me know changes

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 can you review this pr as well

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  can you please review this pr

**Comment by Doraemon012** [comment]
@nishant0708 

A person can like the article more than one time. Also, the like count sometime even becomes negative. This should not happen.
This is probably an issue with promises.

[Screencast from 07-03-2024 10:45:07 PM.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/f0cd133f-aa6a-4a19-a37a-533b3bcfdd12)

**Comment by nishant0708** [comment]
hey @Doraemon012 it should be fine now

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
