### PR TITLE
Removed white spaces

### LINKED ISSUE #244: feat: Enhancing the landing page by eliminating the white spaces
**Is your feature request related to a problem? Please describe.**

There are unwanted white spaces in the landing page:
image

the space above the main heading is disturbing the overall look of the landing page 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Amruta7203**
**What kind of change does this PR introduce?**

Removed the white space above main heading for better visibility

**Issue Number:**

Fixes #244 
**Snapshots/Videos:**

before:
image

after:
image

**Other information**

### CODE REVIEW

**Comment by Amruta7203** [comment]
@Tanay-ErrorCode Review and merge this PR after adding relevant gssoc labels. Thank you

**Comment by Doraemon012** [comment]
@Amruta7203 Please provide screenshot on smaller displays (phone) as well.

**Comment by Amruta7203** [comment]
@Doraemon012 please find the required screen shots below:

image

image

image

image

**Comment by Amruta7203** [comment]
@Tanay-ErrorCode pls add gssoc level label

**Comment by Tanay-ErrorCode** [comment]
@Amruta7203 This is a **one line change** there is no need to give a level for this. You will get 1 point for this.

**Pull request merged**
