### PR TITLE
Added social media links to profile display and css

### PR DESCRIPTION
**Pull request by krithika2543**
**What kind of change does this PR introduce?**
This PR introduces a feature enhancement to the profile display, adding social media links along with appropriate CSS styling.

**Issue Number:**
#75

**Snapshots/Videos:**
image
image

**Other information**
GSSOC'2024 Contribuition

### CODE REVIEW

**Comment by krithika2543** [comment]
@Tanay-ErrorCode I am done with the the task please kindly check

**Comment by Tanay-ErrorCode** [comment]
@krithika2543 Currently on clicking the links, it redirects to `http://localhost:3000/{the url entered by user}` like http://localhost:3000/www.x.com, while it should go to `www.x.com`, and if the links are empty (user has not entered them), it should not redirect but fade the icon (disabled grey color)

**Comment by heysagnik** [comment]
Hey @krithika2543 , The error that when clicked the social media icons it redirects to `http://localhost:3000/{the url entered by user}` is occurring only when the user is updating the instagram url to `instagram.com/heysagnik` while it is working fine when updated to `https://instagram.com/heysagnik` . So, I suggest updating the `EditProfile.tsx` 

```
<Form.Control
  type="text"
  value={instagram}
  onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
    let inputValue = e.target.value;
    if (!inputValue.startsWith('https://')) {
      inputValue = `https://${inputValue}`;
    }
    setInstagram(inputValue);
  }}
/>
```

**Review by heysagnik — APPROVED** [review]
👍

**Comment by Tanay-ErrorCode** [comment]
@krithika2543 Great work !

**Pull request merged**
