### PR TITLE
feat: Redesign Create Event page #218

### PR DESCRIPTION
**Pull request by nishant0708**
-redesigned the UI of create event page
-responsive
**#218**

Fixes #
Screenshot 2024-06-19 034226

**this screenshot was taken when background was  white(temporary)  but in code there is some default background color**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 Can you review this pr

**Comment by Doraemon012** [comment]
@nishant0708 Please add functionality to change the uploaded banner as we can't change it after uploading.

**Comment by Doraemon012** [comment]
@nishant0708 

1. Use `MUI` (Cards, Typography, etc) instead of `html`.
2. For changing the image, add a button `Change`. Remove the `Upload` container when changing the image.
image
3. Please change the `DropZone.js` to `DropZone.tsx`

**Review by Doraemon012 — CHANGES_REQUESTED** [review]
Please make the requested changes.

**Comment by nishant0708** [comment]
On it 🔥🔥

**Comment by nishant0708** [comment]
Hey @Doraemon012  Please check It Now

Screenshot 2024-06-21 235445
Screenshot 2024-06-21 235507

**Comment by nishant0708** [comment]
hey @Doraemon012  @Tanay-ErrorCode  can you please review this pr

**Comment by nishant0708** [comment]
Hey @Doraemon012 can you let me know the changes in this if there are any..

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
