### PR TITLE
feat: Add option to share event #318

### LINKED ISSUE #318: feat: Add option to share event
### **Is your feature request related to a problem? Please describe.**
Currently, there is no functionality to share events. We need to add this functionality to the event details page.

### **Describe the solution you'd like**
Add a share button **only** on the **event details page**.

image

Upon clicking the share button, a modal like the image below should open.

image

### **Describe alternatives you've considered**
None

### **Additional context**
None

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

-Added option to share Event in Event-details page 

#318 

Fixes #318 
**Snapshots/Videos:**
Screenshot 2024-07-07 182831

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012 please check this if want any changes in Ui or in onclick function of social icons

**Comment by Doraemon012** [comment]
@nishant0708 Please make the following changes:

1. When sharing an event via Linkedin or X (twitter) , only `locahost:3000`.
2. The modal should be in page center with faded background.
3. Please use MUI (not React Bootsrap) [MUI Modal](https://mui.com/material-ui/react-modal/)
4. Please make it similar to the image provided in the issue. (except the banner, as it is rectangular in our case)
5. It is not displaying the correct banner image.

image
6. Use these icons:
```tsx
import IosShareIcon from '@mui/icons-material/IosShare';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
```
7. Also add background colors to icons so as to make them look similar to provided image.

image

**Comment by nishant0708** [comment]
Hey @Doraemon012  in 1st point localhost:3000 should be the link right ?

**Comment by Doraemon012** [comment]
@nishant0708 The desired functionality is to share a particular event. So the url to the event should be shared instead of base url.

**Comment by nishant0708** [comment]
> @nishant0708 The desired functionality is to share a particular event. So the url to the event should be shared instead of base url.

Just like it is doing in clipboard right?

**Comment by Doraemon012** [comment]
> >  The desired functionality is to share a particular event. So the url to the event should be shared instead of base url.
> 
> Just like it is doing in clipboard right?

@nishant0708 Yes

**Comment by nishant0708** [comment]
hey @Doraemon012 please check this pr i know you told me to create exact same ui but look at this Ui if you dont like it i will replace with image Ui code 
Screenshot 2024-07-08 024305

Secondly The Link Logic is correct the problem is with '#'  in the url of event details page which is causing a problem .

and if you need any other changes let me know and if you want i could remove this  '#' from link

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please provide a screen recording (all the share options).

**Comment by nishant0708** [comment]
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/fb8e5fa9-d8ff-47da-918c-c1cd77eae039

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please check share functionality on unstop. We need a similar one. Notice the URL(s) for sharing.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/9e8dc0c2-bcb5-411e-8210-58a61ef1f0a2

**Comment by nishant0708** [comment]
Okay got it.. I will complete it by evening

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 I checked The problem is when we share links it does not support Localhost links 
but as soon as i replace it with luposkill Domain name, like this it will work fine 

image

image
And the reason it is going upto  https://lupo-skill.web.app/ is due to that # if there is no # then it will work fine and will show event details 

so please tell me what should i do?

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 See I Am damm Sure If i remove that # from  Routing and then you merge it Will  work Completely fine Just Like A video . So should i do that?

**Comment by Tanay-ErrorCode** [comment]
> hey @Tanay-ErrorCode @Doraemon012 See I Am damm Sure If i remove that # from Routing and then you merge it Will work Completely fine Just Like A video . So should i do that?

@nishant0708 There was no need of changing the routing logic, there was need to add `encodeURIComponent` for the links.

**Review by Tanay-ErrorCode — APPROVED** [review]

**Review by Doraemon012 — APPROVED** [review]

**Comment by nishant0708** [comment]
> > hey @Tanay-ErrorCode @Doraemon012 See I Am damm Sure If i remove that # from Routing and then you merge it Will work Completely fine Just Like A video . So should i do that?
> 
> @nishant0708 There was no need of changing the routing logic, there was need to add `encodeURIComponent` for the links.

hey @Tanay-ErrorCode thanks i will remember this logic from now on

**Pull request merged**
