### PR TITLE
publish event

### PR DESCRIPTION
**Pull request by Vijayaa21**
**What kind of change does this PR introduce?**
Users can create and preview events before publishing them. Once an event is published, it appears on the dashboard, where it is visible to all users. This streamlined process ensures easy management and visibility of events.

**Issue Number:**

Fixes ##355

**Snapshots/Videos:**

https://github.com/user-attachments/assets/9792fb58-1ead-472a-b4bc-7d8371cbdbca

**Other information**

### CODE REVIEW

**Comment by Doraemon012** [comment]
@Vijayaa21 Please, create a new branch, with the latest changes (upstream), add asterisks in the event page, and open the PR once again.

**Comment by Vijayaa21** [comment]
> @Vijayaa21 Please, create a new branch, with the latest changes (upstream), add asterisks in the event page, and open the PR once again.

open another pr with new branch

**Comment by Tanay-ErrorCode** [comment]
@Vijayaa21 Yes, make sure that branch is not behind this repo's commits.

**Comment by Vijayaa21** [comment]
> @Vijayaa21 Yes, make sure that branch is not behind this repo's commits.

yes, it's not.

**Pull request closed without merging**
