### PR TITLE
feat: File add support for events. #397

### LINKED ISSUE #397: feat: File add support for events.
**Is your feature request related to a problem? Please describe.**
Currently, there is no functionality to add files to events. Organizers may need to attach additional files such as PDFs or PPTs to provide detailed information or resources related to the event.

**Describe the solution you'd like**
Add the capability for event organizers to upload and attach files (e.g., PDFs, PPTs) to their events. This feature should allow organizers to:
- Attach relevant files during the event creation process.
- Enable attendees to download and access these files.

**Describe alternatives you've considered**
None

**Additional context**
Set maximum size for files. 

image

Add the **folder** named event attachments.

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

#397 

Fixes #397 
**Snapshots/Videos:**

https://github.com/user-attachments/assets/64ce014f-9b80-42dd-95a7-ca6496ad819b

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  @Doraemon012 please review this pr as soon as possible and let me know  all changes once so that i can deliver this task to you before gssoc ends

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Even after the alert, the incorrect file type can be added. 

image

Fix this behavior, and display **toast** instead of alert.

**Comment by nishant0708** [comment]
Okay I will do it .

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode fixed that .please check it now

**Review by Doraemon012 — APPROVED** [review]

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode i can still complete one more issue so if there is any task then let me know thanks ..

**Pull request merged**
