### PR TITLE
feat: Update react-router-dom to v6 and Fix Some Issue

### LINKED ISSUE #273: feat: Update react-router-dom to version 6 and refactor routing logic
**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.
- Changing normal router as hash router creates difficulties in SEO 

_GSSOC'2024 Contribuitor_

@Tanay-ErrorCode assign this to me.

### PR DESCRIPTION
**Pull request by MinavKaria**
**What kind of change does this PR introduce?**

Changed the routing to v6 where all the routes are now present in `configs/router.tsx` where you need to just add the path and element like 

```
 {
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```

**Issue Number:**  

Fixes #273 

**Main Implementation present in:**  `App.tsx and Navbar.tsx`

**Other information**

Updated the react router dom to version 6 with createBrowserRouter .
Finally , making it easier for the beginners to add a page route and made the routes proper for better SEO

### CODE REVIEW

**Comment by MinavKaria** [comment]
@Tanay-ErrorCode Pls acknowledge

**Review by Doraemon012 — APPROVED** [review]

**Comment by MinavKaria** [comment]
@Tanay-ErrorCode Why did you revert my PR  , everything was fine then too ?

**Comment by Tanay-ErrorCode** [comment]
@MinavKaria It was **working fine on localhost** but once deployed **on the firebase hosting, it said 404 for all the pages other than the homepage**. So I had to revert that.

**Comment by MinavKaria** [comment]
@Tanay-ErrorCode Ohh, I have heard this for the first time, I have used that method many times and hosted on the firebase too, Maybe `firebase.json` maybe different that is why it would be showing that 🤔

**Pull request merged**
