### PR TITLE
feat: Implement UI for In-App Notifications #206

### LINKED ISSUE #206: feat: Implement UI for In-App Notifications
#### **Is your feature request related to a problem? Please describe.**
To add an in-app notification feature, we need to design and implement the user interface.

#### **Describe the solution you'd like**
The solution requires creating the UI components necessary for in-app notifications.

#### **Describe alternatives you've considered**
None.

#### **Additional context**
- Implement the UI as follows:
    - Add a notifications icon button in the navbar.
        - Use this icon: `import NotificationsIcon from '@mui/icons-material/Notifications';`
    - Add a badge on the icon to indicate unread notifications.
        - Use the [MUI badge component](https://mui.com/material-ui/react-badge/).
    - A notifications panel should open when the user clicks the notifications button.
        - Refer to the video example for the notifications panel: 
        
        https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/3fbe6cfa-852e-49d1-8295-babe46f506a8
        
- Ensure the UI integrates with the existing design of the project.
- Use [MUI](https://mui.com/material-ui/all-components/).
- Refrain from using hardcoded values; the theme (colors, font sizes, border radii, etc.) is available in `App.css` and `theme.tsx`.

### PR DESCRIPTION
**Pull request by nishant0708**
feat: Implement UI for In-App Notifications #206

-Added Icon and dummy data for Now

#206

Fixes #206 

Screenshot 2024-06-11 044429

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012  please review this pr and if there are any changes let me know

**Comment by Doraemon012** [comment]
@nishant0708 
1. Make the Notifications Panel as a component in a separate file.
2. The notification will be like -**The event `{name of the event}` has been deleted**. Keep the width of the panel according to this.
3. Also, the panel should have a max width. If the text exceeds it, the text should be multiline (wrapped). Take the notifications panel in [this](https://mui.com/material-ui/material-icons/) website as reference.

**Comment by nishant0708** [comment]
hey @Doraemon012 @Tanay-ErrorCode please Check it now For Now it has dummy data 
image

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 On small width devices like iPhone SE, the hamburger isn't visible. So, on small screen devices, add the notifications button inside the hamburger.

localhost_3000_(iPhone SE)

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode just asking in small screen 
image
you want Notification Like this?

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012 please can you reply because I tried to move notification inside the hamburger menu the notification menu item is not working correctly it is causing a lot of trouble .How about we move dark mode button in hamburger menu ?

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Ok, we can move that theme toggle button inside the hamburger.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012  please check it now
image
image

**Comment by nishant0708** [comment]
Hey @Doraemon012 @Tanay-ErrorCode can I start working on pr #218  till then??

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good work.

**Comment by Tanay-ErrorCode** [comment]
> Hey @Doraemon012 @Tanay-ErrorCode can I start working on pr #218 till then??

@nishant0708 Ok, look into that.

**Pull request merged**
