### PR TITLE
FIXED::feat: Implement Profile Editing Feature #50

### PR DESCRIPTION
**Pull request by nishant0708**
FIXED::feat: Implement Profile Editing Feature #50

#50

- Image Upload Paths:

Updated banner image path to user-banners/user-banner-${uid} to ensure overwriting existing images.

- Data Fetching:

Added fetchUserData function to populate user's existing data when the modal is shown.

- Form Input Handlers:

Added handleImageUpload for image selection.
Added handleTagChange to limit tags to a maximum of 5.

- Submit Logic:

**Modified handleSubmit to:**
Upload images and retrieve URLs.
Save updated user details to Firebase.
Display success and error toasts.
Refresh page on success.
User Feedback:

- Added loading state to disable "Save Changes" button during updates.

Integrated react-toastify for success and error notifications.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/da61a0b9-cbcb-4b3a-8ff1-23161caaa456

**ADDITIONAL BUG FIXED**
Fixed pagination issue in Created events and Joined Events 

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/8700ce12-604d-45a3-adec-fc59a3c5365d

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please use `user-profile-pics` instead of `profileimg`.

**Comment by nishant0708** [comment]
I made the changes you requested; kindly review.

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 LGTM!

**Review by Doraemon012 — APPROVED** [review]
Good work !

**Pull request merged**
