### PR TITLE
Implemented modal to a page

### LINKED ISSUE #198: feat: Convert Create Event Modal to Create Event Page
### **Is your feature request related to a problem? Please describe.**
Make create event page.

### **Describe the solution you'd like**
Convert the create event modal into a separate page while maintaining all existing functionalities.
This is the current create event modal:
image

### **Additional context**
The page should have all the existing functionality of the create event modal.

### PR DESCRIPTION
**Pull request by Tomkndn**
**What kind of change does this PR introduce?**
Feature - Just a conversion of  a modal to a stand alone page for creating a event.

**Issue Number:**

Fixes #198
**Snapshots/Videos:**

Screenshot from 2024-06-12 23-55-24

**Other information**
Made changes to app.tsx, navbar.tsx and createEvent.tsx files.

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn The image cropper is showing in the page itself not as the modal. Kindly fix this.

image

**Comment by Tomkndn** [comment]
Only the cropper image should be in modal right?

**Comment by Tomkndn** [comment]
Fixed the cropper modal, review again and let me know any fixes to be done.

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn Good work.

**Pull request merged**
