### PR TITLE
Homepage Card Animation 

### LINKED ISSUE #390: feat: Homepage card animation
### **Is your feature request related to a problem? Please describe.**
Currently, there is one image of all the event cards, and there is no animation in it. Card images should be separate (but fitted into one `div`, looking exactly like the image) and it must have animation.

The event card images should display one by one with fading animation, one time load, each comes with fade animation and then stays there.

When the user hovers over the card, the z-index of it must increase, i.e., the card must come above others (as there will be corners overlapping (intentional)) slowly with animation.

On smaller devices, it must adjust itself according to the screen width.

### **Describe the solution you'd like**
1. The event card images should display one by one with fading animation, one time load, each comes with fade animation and then stays there.

2. When the user hovers over the card, the z-index of it must increase, i.e., the card must come above others (as there will be corners overlapping (intentional)) slowly with animation.

3. On smaller devices, it must adjust itself according to the screen width.

### **Describe alternatives you've considered**
None

### **Additional context**

image

Here is the zip file of card images:

[cards.zip](https://github.com/user-attachments/files/16486528/cards.zip)

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
**What kind of change does this PR introduce?**

I have break the single image into different components and configured each image seperately and added animations to all images
I have also fixed the zindex so that when user hover on the image so the image looks like popping up 

**Issue Number:** #390 

Fixes #390 
**Snapshots/Videos:**

https://github.com/user-attachments/assets/eeb177f0-1c2d-4700-bfc6-d8d846b6d44a

https://github.com/user-attachments/assets/69b9b210-8412-4623-88e5-24704a416214

https://github.com/user-attachments/assets/9dcc62d1-b694-471c-8881-279037cb2f97

**Other information**

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode @Doraemon012  Please review this and let me know if any changes

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 Fix the issues in layout.

1. Large screens:

image

2. Small screens:

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode is this looking like this in your browser or should i change the position of images like this ?

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode i fixed that but if it is not fixed please send the screen size i will work on that accordingly 

image
image

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 

1. There is no animation in some cards.
2. When the user hovers on a card it **blinks**.
3. When the user hovers on the card it increases z-index as intended **but, if the user moves mouse out of the card, its z-index goes back to normal**

Fix this.

https://github.com/user-attachments/assets/2496aac0-39dc-4e8b-84e2-d391d37b0abc

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/user-attachments/assets/78dc6f88-67dd-44a4-b4c3-6a813081c536

@Tanay-ErrorCode i applied this animation to every image please check and it is changing the z-index on hovering

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 
1. When the user hovers on a card it **blinks**.
2. When the user hovers on the card it increases z-index as intended **but, if the user moves mouse out of the card, its z-index goes back to normal.** It should not go to previous state.

These two are still remaining.

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode Can you please share a video or sc where you want that animation like as of i know their are 6 images in total and i have added blink effect to all of them
Please see the video and tell me if i am missing something

https://github.com/user-attachments/assets/c57be5a3-6d73-45a5-bcef-b012b699e651

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 

### Analogy Explanation

Imagine you have a stack of cards, each with a different importance level. The most important card is on top, and the least important is at the bottom. The importance of each card is represented by its z-index, which determines how "in front" the card appears compared to others.

1. **Initial State:**
    - You have four cards.
    - The z-index array `[4, 3, 2, 1]` indicates their current importance levels, with `4` being the highest and `1` the lowest.

2. **Hover Action:**
    - When you hover over a card, it becomes the most important card (z-index 4).
    - The previous most important card (which had z-index 4) moves down to become the second most important (z-index 3), and so on.

3. **Visualizing with an Example:**
    - **Starting Point:**
        - Cards: `A, B, C, D`
        - Z-Indices: `A: 4, B: 3, C: 2, D: 1`
    - **First Hover:**
        - You hover over card `C`.
        - New Order: `C, A, B, D`
        - Updated Z-Indices: `C: 4, A: 3, B: 2, D: 1`
    - **Second Hover:**
        - Now, you hover over card `B`.
        - New Order: `B, C, A, D`
        - Updated Z-Indices: `B: 4, C: 3, A: 2, D: 1`

4. **Dynamic Adjustment:**
    - Each time you hover over a card, it moves to the top of the importance stack, and the other cards adjust their importance levels accordingly.

### Summary
In essence, when you hover over a card, it takes the topmost position in terms of visibility (highest z-index), pushing down the previously topmost card and adjusting the visibility (z-index) of all other cards. This dynamic reordering ensures the hovered card is always most prominent.

Kindly fix it accordingly.

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode Ohk ok now i understood fixing this

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode  Please check 

https://github.com/user-attachments/assets/6d99c95b-104a-4dcd-951a-c8df82f52175

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode If i understood clearly you are saying this 

https://github.com/user-attachments/assets/22006072-e12d-4b88-b914-f99f57f09625

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 Observer the moment when the opacity becomes 0 just after hovering it. We don't need this type of **blink**

https://github.com/user-attachments/assets/22c1e6d0-dacc-499e-9c12-26498f2923a6

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 Make it similar to the video I provided.

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
Uploading bandicam 2024-08-05 20-50-18-800.mp4…

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 The latest commit isnt working, seems like some mistake, kindly fix it.

image

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode  yes I am fixing error please give me time for today

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 Can you fix this image going out of the screen?

localhost_3000_(iPhone XR)


localhost_3000_(iPhone SE) (2)

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode i fixed that please check i reduced the sized of the images to minimum

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode please check

**Comment by Ayushmaanagarwal1211** [comment]
@Tanay-ErrorCode what happened

**Review by Doraemon012 — CHANGES_REQUESTED** [review]
image

@Ayushmaanagarwal1211 Please adjust the size according to the website.

**Pull request closed without merging**
