### PR TITLE
Changes made in navbar functionality

### LINKED ISSUE #21: bug : Changes in Navbar
**Describe the bug**
Only logged in users can able to create event and access dashboard.So,
Lets hide the dashboard and create event menu when the user was not logged in

**To Reproduce**
1. Go to 'https://lupo-skill.web.app/'
2. See the options "Dashboard" and "Create event" in nav bar

**Expected behavior**
The dashboard and create event option only visible to logged in users.

### PR DESCRIPTION
**Pull request by BHS-Harish**
**What kind of change does this PR introduce?**
The dashboard and create event button clicked when the user logged out. It will show signup model.
Logged in user only accessible to visit dashboard and create event. 

**Issue Number:**
Fixes #21 Changes in navbar

**Screen record**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/114602603/731378fe-a6f0-4f98-a859-aa8fd037ed3c

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@BHS-Harish Please provide a screen recoding of the output.

**Comment by BHS-Harish** [comment]
> @BHS-Harish Please provide a screen recoding of the output.

Yeah sure

**Comment by BHS-Harish** [comment]
@Tanay-ErrorCode   Screen record added buddy

**Comment by Doraemon012** [comment]
@BHS-Harish 

- You need to resolve the conflicts.
 
  This happens when you make changes to a file which is also changed by someone else in their commit. You can resolve the conflicting files through web editor or the command line.
  
  I suggest using the web editor, as the number of conflicting files is less.
  
  When you open the web interface then you will see the conflicting files with the incoming and outgoing changes.\
  `<<<<<<< navbar-correction` indicates the code from your branch and `>>>>>>> main` from the main branch.
  
  image
  
  In your `Navbar.tsx`, the highlighted part is missing, you can simply add that to your changes.
  image
  
  Your final `Navbar.tsx` should look like this:
  image
  
  Do the same with `Signup.tsx`.

<hr/>

- Please update your branch, it has been outdated.

  This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`
  
  To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.
  
  You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.
  
  image
  
  https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by BHS-Harish** [comment]
Hello @Tanay-ErrorCode 

Now Is it okay..?

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@BHS-Harish Great work

**Comment by BHS-Harish** [comment]
> @BHS-Harish Great work!

Thanks a lot for gave me the chance.

**Pull request merged**
