### PR TITLE
Style added to scrollbar

### PR DESCRIPTION
**Pull request by zalabhavy**
**Issue Number:**
issue no #191 

**Other information**

I have styled the scrollbar and also added hover effects on that.

### CODE REVIEW

**Comment by Doraemon012** [comment]
@zalabhavy Please share a screen recording of the output.

**Comment by zalabhavy** [comment]
@Doraemon012 Show Conflict while running npm start.

**Comment by Doraemon012** [comment]
@zalabhavy Please share a screenshot of the error.

**Comment by zalabhavy** [comment]
@Doraemon012 
image

**Comment by Tanay-ErrorCode** [comment]
@zalabhavy Please share full screen screenshot for better understanding.

**Comment by Tanay-ErrorCode** [comment]
@zalabhavy 
Please replace this scrollbar

image

With this one as stated in this [comment](https://github.com/Tanay-ErrorCode/lupo-skill/issues/191#issuecomment-2154797708).

image

**Pull request closed without merging**
