### PR TITLE
feat: Share option for articles. #336

### LINKED ISSUE #336: feat: Share option for articles.
**Is your feature request related to a problem? Please describe.**
Add share option for articles, users should be able to share particular article.

**Describe the solution you'd like**
We have the functionality to share events, create functionality to share the articles.

**Describe alternatives you've considered**
None.

**Additional context**
Share icon must be placed here:

image

The share popup should look like:

image

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

-Added option to share Article in article.tsx page

**Issue Number:**

Fixes #336 
**Snapshots/Videos:**
Screenshot 2024-07-10 215243

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 please review this pr and let me know changes if any

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please move the share icon to right side. As in this image :

image

**Comment by nishant0708** [comment]
@Tanay-ErrorCode okay give me a minute

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode done

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
