### PR TITLE
Render page from top

### PR DESCRIPTION
**Pull request by paulkrishanu4**
FIXES: #193

https://github.com/Tanay-ErrorCode/lupo-skill/assets/169196836/a836adf1-6841-4909-a76e-6d3dbeb505da

### CODE REVIEW

**Review by Doraemon012 — CHANGES_REQUESTED** [review]
@paulkrishanu4 Why did you remove the `.github` folder?

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Comment by paulkrishanu4** [comment]
@Doraemon012 dark mode is not working can I work on that?

**Comment by Tanay-ErrorCode** [comment]
@paulkrishanu4 We are planning to redesign the UI.

**Comment by paulkrishanu4** [comment]
@Tanay-ErrorCode ok so can I work on the UI of home page?

**Comment by paulkrishanu4** [comment]
Homepage

**Comment by Tanay-ErrorCode** [comment]
@paulkrishanu4 This is our **[figma design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=1-2&t=xHr3WeZarp55lX57-0)**, what improvements can you make?

**Pull request merged**
