### PR TITLE
feat: Dynamic Addition of Social Media URL Fields in Edit Profile Modal #163

### PR DESCRIPTION
**Pull request by nishant0708**
feat: Dynamic Addition of Social Media URL Fields in Edit Profile Modal #163

-updated the logic of social media input handling
#163 

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/3fa59ed1-97bc-48c1-b3e3-8415c1a21872

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 We want to create a system with the following functionality:

1. **Link Auto-Classification**: When a user pastes a link, it should automatically classify it as Instagram, Twitter, YouTube, etc.
2. **Dynamic Input Fields**: Start with one input box. Once the user fills this box, another input box should appear below it.
3. **Validation**: If any input field is left empty, it should not be saved.

Additionally, the system should not display any predefined account types (like Instagram or Facebook) initially.

Here's an example video illustrating the desired functionality (though it lacks the auto-extending fields feature):

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/2dba2e47-8418-4827-887c-82d159007e8a

This example video demonstrates the basic functionality but does not include the feature where new fields appear automatically as needed.

**Comment by nishant0708** [comment]
Oo okay get it I will implement it

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode please check it now

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Kindly add maximum limit of 3 URLs

**Comment by nishant0708** [comment]
Rest is working fine right?

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode  please check it now and let me know other changes if required

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode please check it now

**Comment by nishant0708** [comment]
hey @Doraemon012 @Tanay-ErrorCode  now branch is is free from merge conflicts and you can review it now

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Is the functionality to set them working on your end??

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Additionally, 

1. You must store them in **set** to prevent duplicates also, firebase RTDB **don't support** array yet.
2. There is no need to store icon.

image

**Comment by nishant0708** [comment]
Hey @nishant0708 i checked it is not setting I am looking into it

**Comment by nishant0708** [comment]
@Tanay-ErrorCode @Doraemon012 please review it Now it should work smoothly now

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/fa6468e1-fc56-4d12-9259-aba3a508cc3d

**Comment by Doraemon012** [comment]
@nishant0708 Please remove your firebase configuration.

**Comment by nishant0708** [comment]
hey @Doraemon012 please check it now

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Great job!

**Pull request merged**
