### PR TITLE
feat: Develop live event WebRTC interface. #358

### LINKED ISSUE #358: feat: Develop live event WebRTC interface.
**Is your feature request related to a problem? Please describe.**

We currently manage meetings using Google Meet, but we want to enable WebRTC-based meetings to reduce reliance on third-party services.

**Describe the solution you'd like**
Implement a WebRTC-based calling system within our platform that allows for seamless audio and video communication. This system should include features such as screen sharing, recording, and chat functionality. It should be secure, scalable, and provide a user-friendly interface.

**Describe alternatives you've considered**
None

**Additional context**

WebRTC Call Interface

Develop an interface for meetings like the image above. Use MUI components.
For now use the route link "/#/meeting/:id"

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

#358 

Fixes #358 

image

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012  can you please review this pr . As you know gssoc is coming to end so please review it asap please.so that i could make changes suggested by you thanks

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Remove the footer and the navbar for only this page. And better than offcanvas, use box or container at the right side for **chat** so that it can stay always on the screen.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode Can you Give me some reference for (se box or container at the right side for chat so that it can stay always on the screen.) this

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 
image
Done

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 if there are any changes please let me know as soon as possible So that i can deliver you those changes before Gssoc ends

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 Any changes??

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Something has changed the whole colors. Kindly fix it.
image

**Comment by nishant0708** [comment]
Okay @Tanay-ErrorCode

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode Done Fixed it

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good job.

**Pull request merged**
