### PR TITLE
feat: Add edit article feature #324

### LINKED ISSUE #324: feat: Add edit article feature
### **Is your feature request related to a problem? Please describe.**
Currently, users do not have the ability to edit articles once they have been published. This can lead to issues if there are errors or updates needed for the content.

### **Describe the solution you'd like**
* Implement an "Edit Article" feature that allows users to modify the content of their published articles.

* Add an edit button in the article reading page, that should be visible only when creator is viewing the article.

### **Describe alternatives you've considered**
None

### **Additional context**

The articles are stored in this way:

image

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

closes #324 
-updated ArticleWriting page to handle update as well

**Issue Number:**

Fixes #
**Snapshots/Videos:**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/07f739eb-c1e5-463b-92b7-e5e8002df30a

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 please review this pr and let me know changes if any

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 When the article is liked by anyone and then if we update the article, all likes are gone. Fix this.

**Comment by nishant0708** [comment]
Okay!!

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode see now whenever anyone is editing article only the Title and Content is going to change let me know if any other change needed thanks

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012  I Guess It Should  work Perfectly Now please review it and let me know change if needed Any

**Review by Doraemon012 — APPROVED** [review]

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  can i work on issue 282 as it has been a week since contributor responded

**Pull request merged**
