### PR TITLE
feat: Add Preview Functionality to Event Creation Page #353

### LINKED ISSUE #353: feat: Add Preview Functionality to Event Creation Page
**Is your feature request related to a problem? Please describe.**
There is no way to preview an event before publishing it. This makes it hard to check if all details are correct.

**Describe the solution you'd like**
Add functionality to preview button in create event page. This should show how the event will look once it's published, so users can review and make changes if needed.

**Describe alternatives you've considered**
None

**Additional context**
On clicking the preview button, The same card displayed on the event page muse appear with the details entered by the user.

### PR DESCRIPTION
**Pull request by nishant0708**
feat: Add Preview Functionality to Event Creation Page #353

hey In This I  Used Modal That Was there For Cropping

**Issue Number:**

Fixes #353 
**Snapshots/Videos:**
Screenshot 2024-07-17 031854

**Other information**

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 

image

1. Fix the hostname always displayed as "HostName".
2. Disable that register button in preview.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode should I leave hostname as blank or should I fetch it and add name

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You have the username in the local storage.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  @Doraemon012 Done It should be fine now
Screenshot 2024-07-17 155120

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You have set the `isDashboard=true`. Do not do this. We do not want to have the link of **non-existent** event. You have to **disable** the register button not to **remove** it.

**Comment by nishant0708** [comment]
Uhh okay got it @Tanay-ErrorCode I will do it

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012  i have disabled the button by passing ispreview prop but it is  turning register button to unregister button  
so i have added a commented code in eventcard that will keep button register if is preview prop is passed so please check it and let me know the changes

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 LGTM

**Pull request merged**
