### PR TITLE
Arrow slider added on Happy User cards 

### LINKED ISSUE #145: bug : There is no arrow slider visible for the happy user card section
**Describe the bug**

There should be a arrow showing slide to left or right

**To Reproduce**

1. Go to  [website](https://lupo-skill.web.app/)
2. on click left or right the card should move accordingly
3. But there is now  arrow given for that.

**Expected behavior**
There should be the left and right arrow given on "Happy user" section so that user experience can be made better.
Some thing like this 
image

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
**What kind of change does this PR introduce?**
it adds new slider for Happy user section cards 

**Issue Number:**

Fixes #145

### CODE REVIEW

**Comment by Maheshwari-Love** [comment]
@Tanay-ErrorCode please add label and merge PR

**Comment by Doraemon012** [comment]
@Maheshwari-Love Please share a screen recording of the final output.

**Comment by Tanay-ErrorCode** [comment]
@Maheshwari-Love The buttons are not visible.

image

**Comment by Maheshwari-Love** [comment]
@Tanay-ErrorCode give me sometime I will checkout it out

**Comment by Tanay-ErrorCode** [comment]
@Maheshwari-Love Any updates?

**Pull request closed without merging**
