### PR TITLE
Fixed::feat: Image Compression before upload #96

### PR DESCRIPTION
**Pull request by nishant0708**
Fixed::feat: Image Compression before upload #96

#96

-modified image cropper to accept aspect ratio as prop;
-add a function to compress-cropped image and then store it in database

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/2846d2a2-f561-48d2-83ba-a643ed0bee34

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Kindly do the changes that the issue mentions. The functionality of **cropperJs** is quite different, the user is able to select the background outside the image and even crop the image to very small size, while **react-easy-crop** offers much simpler and easy to use functionality. 
So, please **implement react-easy-crop** instead of **cropperjs**
Also, add the same functionality of cropping and compressing to event banners.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/1c605bbb-0f1c-4ab3-83c7-df90a55bfa4d

**Comment by nishant0708** [comment]
Okay ..I will do that

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode  @Doraemon012  Please review this and suggest any changes if necessary

**Comment by nishant0708** [comment]
Hi @Tanay-ErrorCode , I Checked that the banner image was using the same functionality as the cropped image. I am sending the aspect ratio as a prop when compressing the banner picture, and I have included a condition that says that the maximum compression size for a banner image should be 200 kb, otherwise it should be 100 kb.Are you requesting anything else? If so, please elaborate.

**Comment by Tanay-ErrorCode** [comment]
> Hi @Tanay-ErrorCode , I Checked that the banner image was using the same functionality as the cropped image. I am sending the aspect ratio as a prop when compressing the banner picture, and I have included a condition that says that the maximum compression size for a banner image should be 200 kb, otherwise it should be 100 kb.Are you requesting anything else? If so, please elaborate.

@nishant0708 Yes, the banner images are also for events. We need to compress them too.

**Comment by nishant0708** [comment]
@Tanay-ErrorCode  @Doraemon012 Please review this and suggest any changes if necessary.

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good work !

**Pull request merged**
