### PR TITLE
Feature : Improved Tag input system

### LINKED ISSUE #65: feat: Improving Tag Input System
## **Is your feature request related to a problem? Please describe.**
Right now, we have to separate tags with commas when entering them. This is annoying and less user friendly.

## **Describe the solution you'd like**
I'd like a tag input feature similar to YouTube, where pressing Enter automatically creates a new tag. This would make tagging much easier and more user friendly.

image
Use this design :
image

## **Additional context**
- **Please note, the theme colors should not change with this update.**
- And in the database, **currently the tags are stored as comma separated, this format should not change** .
image

### PR DESCRIPTION
**Pull request by Tomkndn**
**What kind of change does this PR introduce?**
Improved the ui for the create event input tag system as mentioned.

Fixes #65 
**Snapshots/Videos:**
image

**Other information**

If the user presses the enter button the new tag will be created as per the text entered and also when clicked on the cross button, It deletes the respective tags.

### CODE REVIEW

**Comment by Doraemon012** [comment]
@Tomkndn Please do the same for edit profile modal as well.

**Comment by Tomkndn** [comment]
But the issue was of input tags.

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn We have tags in the Edit profile popup as well as in the create event popup.

**Comment by Tomkndn** [comment]
Okay got it, I will add there soon.

**Comment by Tomkndn** [comment]
Added the same ui to the edit profile modals too.
image

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn Currently when entering many tags or ones with more length, they go out of the modal.

image

Kindly, Get them in **new line if they are long enough** and please **set a limit of maximum 5 tags in both profile and event**.

**Comment by Tanay-ErrorCode** [comment]
> In the profile maximum tags should be 5. So i will fix the tag in event modal to only upto 5?

@Tomkndn Yes, both inputs must have that limit.

**Comment by Tomkndn** [comment]
I think now its solved.

**Comment by Tomkndn** [comment]
okay understood, this is happening because earlier you added 4 tags and now it is fetching from database and ensuring that you should have only 5 tags.
So, it is allowing only 1 tag.

**Comment by Tomkndn** [comment]
Fixed the current issue.

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn Great work !

**Pull request merged**
