### PR TITLE
FIXED::bug : Spinner Persists on Profiles with No Events #45

### PR DESCRIPTION
**Pull request by nishant0708**
bug : Spinner Persists on Profiles with No Events #45

#45

- Added conditional rendering to display a message when no created events are found.
- Added conditional rendering to display a message when no joined events are found.
- changed the state of spinner when no data is found

### CODE REVIEW

**Comment by Doraemon012** [comment]
@nishant0708 Please provide screen recording of the final output.

**Comment by nishant0708** [comment]
Hey here is the recording you asked for..
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/4b851efa-af33-403d-bb1e-da6287d1b64b

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please update your branch, it has been outdated.

  This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`
  
  To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.
  
  You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.
  
  image
  
  https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please update your branch, it has been outdated.

  This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`
  
  To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.
  
  You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.
  
  image
  
  https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by nishant0708** [comment]
I have updated my branch please check

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good work!

**Pull request merged**
