### PR TITLE
feat: Implement backend for notifications #363

### LINKED ISSUE #363: feat: Implement backend for notifications
### **Is your feature request related to a problem? Please describe.**
Implement the backend for in-app notifications.

### **Describe the solution you'd like**
- Store a users' notifications in the user object in firebase.
- A notification object should be similar to this:
  ```tsx
  {
    title: "Title of notification",
    text: "Text to be displayed", // (eg. The event `Summer Camp 2024`  has been deleted)
    date: timestamp(),
    link: url() // (new url of the event, if it is rescheduled)
  }
  ```
- **A user should receive notification when the users' registered event is deleted.**
- The displayed notifications should be sorted by time.
- **The notification should be automatically deleted after 7 days.**

### **Describe alternatives you've considered**
None 

### **Additional context**
None.

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

Implement backend for notifications

#363 

Fixes #363 
**Snapshots/Videos:**

https://github.com/user-attachments/assets/0a81908a-977d-49de-9048-531985379d6e

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  @Doraemon012  please review this pr as soon as possible . as you Know Competition coming to end so please let me know changes if any.

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 
1. Set max-limit for the notifications (5).
2. Are the notifications automatically deleted after 7 days?

**Comment by nishant0708** [comment]
> @nishant0708
> 
> 1. Set max-limit for the notifications (5).
> 2. Are the notifications automatically deleted after 7 days?

Added  code for that  7 day

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  @Doraemon012   have Set max-limit for the notifications (5).
Are the notifications automatically deleted after 7 days? yes They Are

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  @Doraemon012  please review this pr as soon as possible .please

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
