### PR TITLE
added share option

### LINKED ISSUE #248: feat: share option to share event
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
Fixes #248

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Please provide screen recording of the output.

**Comment by Rohitha-pudu** [comment]
WhatsApp Image 2024-06-23 at 12 10 15_97ce4722

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Provide screen recording instead of screenshot.

**Comment by Rohitha-pudu** [comment]
Uploading Events _ Lupo Skill — Mozilla Firefox 2024-06-23 13-37-13.mp4…

**Comment by Rohitha-pudu** [comment]
https://github.com/Tanay-ErrorCode/lupo-skill/assets/116823590/7a97780d-eb09-48f1-a768-7ef42115b4b0

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Only the event we are sharing should be shared not the whole page.

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Please do the changes as requested in **[this comment](https://github.com/Tanay-ErrorCode/lupo-skill/issues/248#issuecomment-2184492360)**.

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu Only the event we are sharing should be shared not the whole page. Please fix

For that the event should have a separate page

**Comment by Tanay-ErrorCode** [comment]
> > @Rohitha-pudu Only the event we are sharing should be shared not the whole page. Please fix
> 
> For that the event should have a separate page

@Rohitha-pudu Have you read **[this comment](https://github.com/Tanay-ErrorCode/lupo-skill/issues/248#issuecomment-2184492360)** properly?

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Any updates?

**Pull request closed without merging**
