### PR TITLE
bug: Updating the logic for profile pictures #317

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

FIXED ISSUE #317 
Updated it for both single article page
and all article pages

**Issue Number:**

Fixes #
**Snapshots/Videos:**
Screenshot 2024-07-07 041744
Screenshot 2024-07-07 041653

**Other information**

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 In the `EditProfile` when the user updates its profile picture, then it should be also written to the articles he has created. In your logic we double the number of reads which will cause higher costs and slow down the server.

**Comment by nishant0708** [comment]
Okay

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode i Guess this should work in optimized way please check and let me know

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012  can you review this pr

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
