### PR TITLE
Update react-router-dom to version 6 and refactor routing logic

### PR DESCRIPTION
**Pull request by MinavKaria**
## Description (Issue #273  )

Updated the react router dom to version 6 with createBrowserRouter 

## Motivation and Context

It is important to stay updated and version 6 makes the route creation **very easy** by just adding
Also removed the hashrouter where all the links started with #/ which causes which is not good for the SEO.

```
 {
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```
Thus making it easier for the beginners to add a page route and made the routes proper for better SEO

## How Has This Been Tested?

Checked every route before committing , Fortunately all the routes work properly as previous.

## Screenshots (if appropriate):

No visual feature as such so will be need to run on local environment to check the changes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MinavKaria** [comment]
@Doraemon012 @Tanay-ErrorCode why closed ?

**Comment by Doraemon012** [comment]
@MinavKaria We didn't close this. You deleted the fork of the repo, which is why the PR closed automatically.

deleted

**Comment by Doraemon012** [comment]
@MinavKaria 
You can see the changes made in this PR in the `Files changed` tab. To open a PR with the same code, fork the repository again, make the same changes, and then open the PR.

**Comment by MinavKaria** [comment]
Ohh 😅😅, I'll once again send the PR

**Pull request closed without merging**
