### PR TITLE
feat: Opening writer profile from the article reading page. #287

### LINKED ISSUE #287: feat: Opening writer profile from the article reading page.
**Is your feature request related to a problem? Please describe.**
Currently we can't visit the profile of the writer of the article. We need this basic functionality.

**Describe the solution you'd like**
On clicking either the Profile picture of user or on the name, it should open the profile of that user (The same functionality is in the event card.).

**Describe alternatives you've considered**
None

**Additional context**
image

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**

#287 

Fixes #287 
**Snapshots/Videos:**

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 please review this pr

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 We want this functionality in the article reading page too (single article), as stated in the issue.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  please check it now it should work fine in single Article page to

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 good work,

**Pull request merged**
