### PR TITLE
fixed circular loading indicator

### LINKED ISSUE #37: bug : Center loading indicator
**Describe the bug**
The loading indicator is below the nab bar. It should be centered for better user experience

**To Reproduce**
i will change the styles of the loading indicator

**Expected behavior**
it should be at center of the screen

**Screenshots**
image

### PR DESCRIPTION
**Pull request by himanshugoyal77**
**What kind of change does this PR introduce?**
added css styles to fix position of loading indicator

**Issue Number:**
fixes #37 

**Snapshots/Videos:**
image

**Other information**

### CODE REVIEW

**Comment by Doraemon012** [comment]
@himanshugoyal77 

Please update your branch, it has been outdated.

This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`

To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.

You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.

image

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by heysagnik** [comment]
@himanshugoyal77 please resolve the conflicts

**Comment by Tanay-ErrorCode** [comment]
@himanshugoyal77 Good work !

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Pull request merged**
