### PR TITLE
Sorted Events according to their CreatedAt time.

### LINKED ISSUE #30: feat: Sort events by `createdAt`
##  **Is your feature request related to a problem? Please describe.**
Currently, the events in our website are not sorted, making it difficult for viewers to quickly find relevant events.

## **Describe the solution you'd like**
The events on our website should appear in sorted order by default. This means that when users visit the `events page`, `dashboard page` or the `user profile page`, they will see the events already sorted according to the `createdAt` time. 

### **Pages to be affected**
- Events Page
- Dashboard Page
- User Profile Page

## **Describe alternatives you've considered**
None

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by sahilhedau49**
**What kind of change does this PR introduce?**

I need to sort the events data accroding to createdAt after feteching it.
While doing same, some errors related to type of data was occured. To resolve it I make an interface named as Event, and used it accrodingly.

**Issue Number:**
Fixes #30
 
**Snapshots/Videos:**
This is the result, shows sorted data.
image

### CODE REVIEW

**Comment by Doraemon012** [comment]
@sahilhedau49 

 - Please update your branch, it has been outdated.
    
    This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`
    
    To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.
    
    You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.
    
    image
    
    https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd
  
  - Please remove your Firebase Config. Firebase keys are confidential and are only necessary for running the project locally on your computer. They shouldn't be shared publicly or pushed to any public platform.

**Comment by Doraemon012** [comment]
@sahilhedau49 The events are being sorted in reverse order. Please sort them so that the recently created events appear first in the list.

**Comment by sahilhedau49** [comment]
Ok

**Comment by sahilhedau49** [comment]
@Doraemon012  Can you please review now.

**Comment by Doraemon012** [comment]
@sahilhedau49 The issue was to sort the events in `dashboard`, `user profile` and `events` page. You have only done it for the dashboard. Please complete the remaining part.

**Comment by Doraemon012** [comment]
@sahilhedau49 Please fix the conflicting file.

**Comment by sahilhedau49** [comment]
Resolved

**Comment by Tanay-ErrorCode** [comment]
@sahilhedau49 Good work!

**Pull request merged**
