### PR TITLE
Navbar On scroll Effects added

### LINKED ISSUE #374: feat: Modify the navbar for Better visibility on scroll
**Is your feature request related to a problem? Please describe.**
yes , readability issue with the navbar
image

**Describe the solution you'd like**
when scrolled, the UI of navbar should accept a background color to improve visibility

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by sau-mili**
**What kind of change does this PR introduce?**
Navbar made visible on scroll now, with new javascript functions and css.

**Issue Number:**

Fixes #374 
**Snapshots/Videos:**
## when loaded
Screenshot 2024-08-01 023617

## when scrolled
Screenshot 2024-08-01 023625

**Other information**

### CODE REVIEW

**Comment by Doraemon012** [comment]
@sau-mili Please change the background color of the navbar to `#00000059`. So that the result looks like:

image

**Comment by sau-mili** [comment]
Hi, changing it to the mentioned color would lead to unreadable portions when navbar comes over card designs with white background.

**Comment by Tanay-ErrorCode** [comment]
> Hi, changing it to the mentioned color would lead to unreadable portions when navbar comes over card designs with white background.

@sau-mili The sample image is above, it **will look like that**. There is no need to change anything other than `background-color`.

**Comment by sau-mili** [comment]
Do you mean to change the dark background behind the logo, options and the two icons?

**Comment by Tanay-ErrorCode** [comment]
> Do you mean to change the dark background behind the logo, options and the two icons?

@sau-mili Change the full navbar's `background-color`, as shown in this image:

image

**Comment by sau-mili** [comment]
Oh okay okay

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
