### PR TITLE
Added hover effect on "star on GitHub" and "contribute Now" button on homepage

### LINKED ISSUE #224: feat: Adding hover effect on "Star on GitHub" and "Contribute Now" button
**Is your feature request related to a problem? Please describe.**
"Star on GitHub" and "Contribute Now" button on the home page do not have hover effects which is different from other buttons in the UI. 

**Describe the solution you'd like**
Adding style to the create hover effect to these buttons similar to other buttons on the page which will enhance user experience.

**Describe alternatives you've considered**
Changing background color and adding shadow on hover over the button.

**Additional context**
image

### PR DESCRIPTION
**Pull request by Monika5S**
**What kind of change does this PR introduce?**
Hover Effect are added to the start on github and contribute now button on the homepage similar to as of Template card hover. It's done by adding borderStyleChange prop to custom button and a class to style the border on button component which toggles as per mouseEnter and mouseLeave event, A new button.css is applied to make animated border style.

**Issue Number:**
#224 

Fixes #224 
**Snapshots:**
Before Hover
image

After Hover
image

Similar effect is added on contribute now button as well!

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@Monika5S Please provide a screen recording of the output.

**Comment by Monika5S** [comment]
https://github.com/Tanay-ErrorCode/lupo-skill/assets/92215187/db3f5639-8cb4-4ecc-885a-307d236e09a7

**Comment by Tanay-ErrorCode** [comment]
@Monika5S Please make the following changes.

1. Do not change the color of the button **neither on hover nor on no hover**
2. Please make the hover effect like that of testimonial cards.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/6d9d7d0f-b70e-4d3e-8c8d-52cee95c7be3

**Comment by Monika5S** [comment]
I can make button to not to change color. Also I have added the same style that testimonial card have for animation. Can you elaborate more what exactly you're looking on this aspect.

**Comment by Monika5S** [comment]
@Tanay-ErrorCode I've made some changes and this is the ouput:

https://github.com/Tanay-ErrorCode/lupo-skill/assets/92215187/515fef22-45d1-4be0-a23b-bc539d03f70e

Is it required any other change?

**Comment by Tanay-ErrorCode** [comment]
@Monika5S Please use the same colors as in testimonial card hover.

`linear-gradient(290.7deg,rgb(255, 242, 0), rgb(0, 172, 249) 100.2%)`

**Comment by Monika5S** [comment]
@Tanay-ErrorCode I've updated the speed and made changes to implement above said gradient here's the output:

https://github.com/Tanay-ErrorCode/lupo-skill/assets/92215187/0d369f3a-4a63-4fdd-b14b-7f7b8e4abe28

Kindly review it. Thanks!

**Comment by Tanay-ErrorCode** [comment]
@Monika5S Please see the difference between the hover effects of card and button. Please make it similar to card hover effect.

**Comment by Monika5S** [comment]
I have used the same colors, speed and also the animation is similar. Can you elaborate on the changes that are required.

**Pull request closed without merging**
