### PR TITLE
Added reloading features

### PR DESCRIPTION
**Pull request by AnirbanChattopadhyay-2004**
**What kind of change does this PR introduce?**

**Issue Number:**
#223 
Fixes #
**Snapshots/Videos:**

**Other information**

Fixed the issue of reloading the page when clicking on the title button

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@AnirbanChattopadhyay-2004 Please do it like GutHub.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/b5028c2c-9506-44d3-9d5b-32e6e4c52d50

What is currently happening is this:

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/f8e31059-e4b8-4677-81bb-bfa2fa93607d

**Comment by AnirbanChattopadhyay-2004** [comment]
okk I will do it by tommorrow

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 Any updates ?

**Comment by Tanay-ErrorCode** [comment]
@AnirbanChattopadhyay-2004 If you are not able to work on this, please let us know.

**Comment by Tanay-ErrorCode** [comment]
Close

**Pull request closed without merging**
