### PR TITLE
feat: Add support for article writing (backend) #261

### PR DESCRIPTION
**Pull request by nishant0708**
feat: Add support for article writing (backend) #261

#261 
-Added Backend Codes

Fixes #
**Snapshots/Videos:**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/a26a4bf0-21ed-4611-8bec-e50c48318a57

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 please review this pr and let me know the changes

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 

1. As mentioned in the issue there is no article reading page.
2. The cards in the article homepage, are showing full title, as well as the content. This should not happen, if the title is longer than two lines it should be truncated be `...` and if the content is longer than 4 lines, it should do the same too. The text displayed should not be in `.md` text.
image
3. On hover on the card, the mouse should turn into pointer.
4. If the user is not logged in, on clicking on create article button, it should open the signin/signup popup directly.
5. When saving the data, the key by which profile pic is saved must be **`pic`** because it is the same in signup function.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  i have one question if some user Add html content in create article content then how should it be shown in card
1)
Screenshot 2024-06-25 213559

2)
Screenshot 2024-06-25 213255

i have added ### Tools

> These are the tools required to learn Computer Architecture. They are listed below:

<table width="100%">
      <tr>
        <th>Resource Name</th>
        <th>Description</th>
      </tr>
      <tr>
        <td><a href="https://www.simics.net/">Simics</a></td>
        <td>A full-system simulator used to simulate computer systems, enabling software development and testing.</td>
      </tr>
      <tr>
        <td><a href="https://www.cadence.com/">Cadence</a></td>
        <td>A suite of tools for electronic design automation, used for designing and simulating integrated circuits.</td>
      </tr>
      <tr>
        <td><a href="https://www.synopsys.com/">Synopsys</a></td>
        <td>Provides tools for semiconductor design and verification, including simulation and synthesis tools.</td>
      </tr>
      <tr>
        <td><a href="https://www.model.com/">ModelSim</a></td>
        <td>A multi-language HDL simulation environment by Mentor Graphics.</td>
      </tr>
      <tr>
        <td><a href="https://www.xilinx.com/">Xilinx ISE</a></td>
        <td>A software tool produced by Xilinx for synthesis and analysis of HDL designs, enabling the compilation of designs into bitstreams.</td>
      </tr>
      <tr>
        <td><a href="https://www.ni.com/en-us/shop/academic/electronics-lab/ti-tina-ti.html">TINA-TI</a></td>
        <td>A circuit simulation tool that allows you to design, test, and simulate analog, digital, and mixed circuits.</td>
      </tr>
      <tr>
        <td><a href="https://fritzing.org/">Fritzing</a></td>
        <td>An open-source hardware initiative that makes electronics accessible as a creative material for anyone.</td>
      </tr>
</table> in article content

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Keep the second one.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  check it out and let me know if any changes needed

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/cecd91b5-319e-4aa2-83ab-5cdc05fdef5b

**Review by Doraemon012 — APPROVED** [review]

**Pull request merged**
