### PR TITLE
Added social media field and improved the validity of social media url.

### LINKED ISSUE #115: bug : Not verifying whether it is instagram link or not.
**Describe the bug**
In the profile, in the edit section it is not being verified that it is an instagram link and upon putting any other link it is considering it and redirecting to that particular link.
**To Reproduce**

1. Go to lupo website.
2. Click on profile
3. Scroll down to edit
4. Apply any link in the link section for any social media.
5. open it
6. it will redirect to that link without having a check of the typed link.
7. See error

**Expected behavior**
on clicking save if it is not the link it should show an alert for that.
**Screenshots**
Add screenshots to help explain your problem.
[Screenshot 2024-05-25 113453](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/2124791d-6a88-449c-9c90-b624fbe934a4)

**Additional context**
Please assign this issue to me so that I can have a contribution under gssoc24.

### PR DESCRIPTION
**Pull request by AnirbanChattopadhyay-2004**
**What kind of change does this PR introduce?**

Added social media field in the edit profile section under the profile section of the website and improved the validity of the URL acceptance. It means now if it is not the social media url then it will not accept it giving  a warning to input correct social media url  respectively.
**Issue Number:**

Fixes #115 

[Screenshot 2024-05-26 133034](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/184ae761-c17e-448c-8655-8c752a92e9ae)
If the instagram url is given wrong as shown in the screen shot above.
[Screenshot 2024-05-26 133050](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/86cbb835-5f4b-4a88-b011-69a2105fba19)
Then it will show error as show in the screenshot above.
**Other information**

### CODE REVIEW

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 

The functionality should be:
1. If you enter an incorrect URL (e.g., Instagram: abc.com), a toast will notify you that the URL is incorrect.
2. When you close the popup, the entered URL will stay in the text box, allowing you to correct it easily.
3. **The information will be updated only if you enter a valid URL(s) and click the save button**.

**Comment by AnirbanChattopadhyay-2004** [comment]
Ok sir I will make it sure that the url will only change when it is a valid
url other wise it will remain same.

**Comment by AnirbanChattopadhyay-2004** [comment]
I have resolved this issue please merge the PR

**Comment by Tanay-ErrorCode** [comment]
@AnirbanChattopadhyay-2004 Great work.

**Pull request merged**
