### PR TITLE
Hover effect Added 

### PR DESCRIPTION
**Pull request by Damini2004**
**What kind of change does this PR introduce?**

Feature enhancement in happy user section
#185  

**Issue Number:** #185 

Fixes #185 
**Snapshots/Videos:**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/cd86c68f-4137-41b5-8edb-5fb26819f76e

**Other information**

KInldy go through the PR.

### CODE REVIEW

**Comment by Doraemon012** [comment]
@Damini2004 

1. You have changed the colors. Please use the colors mentioned in the issue. 
   - `backgroundImage: "linear-gradient(290.7deg,rgb(255, 242, 0), rgb(0, 172, 249) 100.2%)"`
   
2. Do not use hue rotate. See this [video](https://www.youtube.com/watch?v=1C8lGN-1Sq0). Try to create this effect.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/8363c3e4-9618-460e-aae8-1771951a8f46

3. Do not raise separate PRs for every change, instead push your commits in a single PR.

**Comment by Damini2004** [comment]
1.I didn't change the color, i used those color which is mentioned earlier that you can see in the css file too. Its getting change due to animation effect.
2. Sure but to implement rotation i have added variable like this --a:0deg.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/435f9e24-e824-4a4c-9eb8-26bfdc967ee4

3. Actually earlier PR was creating several errors that why i have to create new PR.

is this hover effect is good ? @Doraemon012

**Comment by Doraemon012** [comment]
@Damini2004 Please do not use hue rotate.

**Comment by Doraemon012** [comment]
@Damini2004 
Ok, please share a screen recording after making the final commits.

**Comment by Doraemon012** [comment]
Good work.

Please try to make it similar to this one.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/8363c3e4-9618-460e-aae8-1771951a8f46


diff

The key differences are:
- In the video that i shared, the colors are blending and animation is slow.
- Also, the cards are rising slowly instead of popping up.

**Comment by Damini2004** [comment]
https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/4dbb7e76-c2e1-4b93-a654-597feb3d1b2e

**Comment by Damini2004** [comment]
Actually the pop up effect is due to fast switching between the cards.
In order to achive the color blending we have to restructure it in the .tsx page that may affect the other functionalities too.
We can achive blending throgh huerotate but the color may change.

Here i reduce the pop up effect go through it.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/c5c19321-8b73-40b9-bfc1-6d66c992c722

@Doraemon012

**Comment by Tanay-ErrorCode** [comment]
@Damini2004 You have to make this. If you are any issues, please let us know.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/966ac22a-7d41-49bc-8eb8-1e8cd3a37884

**Comment by Damini2004** [comment]
Their is only issue of colour blending. @Tanay-ErrorCode

**Comment by Tanay-ErrorCode** [comment]
@Damini2004 Commit your changes. We will let you know if any changes are required.

**Comment by Damini2004** [comment]
@Tanay-ErrorCode  Added Commit.

**Comment by Damini2004** [comment]
Kindly upgrade the level @Tanay-ErrorCode

**Pull request merged**
