### PR TITLE
feat: Alert on unpublished events, articles. #352

### LINKED ISSUE #352: feat: Alert on unpublished events, articles.
**Is your feature request related to a problem? Please describe.**
When writing an article or creating an event, users may lose their changes if they navigate to another page without publishing.

**Describe the solution you'd like**
Show an alert message when a user tries to leave the page without publishing. The message should say, "Your changes have not been saved. Are you sure you want to leave this page?"

**Describe alternatives you've considered**
None.

**Additional context**
This feature will help prevent data loss and ensure users save their changes before leaving the page.

### PR DESCRIPTION
**Pull request by nishant0708**
**What kind of change does this PR introduce?**
working fine

**Issue Number:**

Fixes #352 
**Snapshots/Videos:**

https://github.com/user-attachments/assets/36c89535-3910-412a-bd9b-92c3c09cc011

**Other information**

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 please review it whenever possible. and thanks tanay for help it is one of the difficult task that i attempted to do thank you so much. and let me know changes if any

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 The popup should also come when user tries to navigate to profile page. Kindly add this.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 it should work fine now please check..

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 can you please review it

**Review by Doraemon012 — APPROVED** [review]

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good work.

**Pull request merged**
