### PR TITLE
feat: User can edit created event date, time and description. #85

### PR DESCRIPTION
**Pull request by nishant0708**
feat: User can edit created event date, time and description. #85

-ADDED AN EVENTUPDATEMODEL
-Add icon on profile page to edit event

#85 

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/33086729-b45d-40a9-bef9-de93429a7cfc

### CODE REVIEW

**Comment by Doraemon012** [comment]
@nishant0708 

- Add the edit icon inside the card itself. Like this:
image

- Please add the feature stated in [this](https://github.com/Tanay-ErrorCode/lupo-skill/issues/85#issuecomment-2120903894) comment.
The edited flag should be there to indicate that the event is edited.
image

**Comment by nishant0708** [comment]
Okay working on it

**Comment by nishant0708** [comment]
@Doraemon012 @Tanay-ErrorCode  check this commit 
Screenshot 2024-06-01 212226
Screenshot 2024-06-01 212427

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 The edited flag should be displayed wherever the event cards are (dashboard, events page and the profile)

**Comment by nishant0708** [comment]
@Tanay-ErrorCode Done

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Please move the `EditEventModal.tsx` file inside `src/components/Cards/EditEventModal` folder.

**Comment by nishant0708** [comment]
@Tanay-ErrorCode done.

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Good work !

**Pull request merged**
