### PR TITLE
Filter option

### PR DESCRIPTION
**Pull request by Priya-49**
Added filter option

I added a filter option to the events section. Now the events get filtered when the respective option gets selected.

#24 

Fixes 

Screenshot (209)

### CODE REVIEW

**Comment by Doraemon012** [comment]
@Priya-49

If there are no events found in specific category, please display the message as follows:

- For upcoming - **No upcoming events found**
- For past events - **No past events found**
- For ongoing events - **No ongoing events found**

image

**Comment by Priya-49** [comment]
I have added the "events not found"messages to the respesctive events.

**Comment by Tanay-ErrorCode** [comment]
@Priya-49 

Please update your branch, it has been outdated.

This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`

To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.

You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.

image

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by Priya-49** [comment]
@Tanay-ErrorCode
There's no update branch option here. Could you check into it.
Screenshot (213)

**Pull request merged**
