### PR TITLE
Fixed bug : Star on Github button not working #70

### PR DESCRIPTION
**Pull request by ansh-h-mehta**
**What kind of change does this PR introduce?**
On clicking on the Star on github button it is not redirecting to the Github account. I resolved that issue.
Added href to the button to redirect user so that they can star on Github

**Issue Number:**
Fixes Bug #70 

Fixes #
**Snapshots/Videos:**

image

### CODE REVIEW

**Comment by ansh-h-mehta** [comment]
@Doraemon012, @Tanay-ErrorCode Kindly review my PR 😇

**Comment by Doraemon012** [comment]
@ansh-h-mehta Please add the link in the Star on GitHub button like this.

image

**Comment by ansh-h-mehta** [comment]
Hey @Doraemon012  I've made the necessary changes according to the provided snippet. Please review it.

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Comment by Tanay-ErrorCode** [comment]
@ansh-h-mehta Good work!

**Comment by ansh-h-mehta** [comment]
> @ansh-h-mehta Good work!

Thank you 😇

**Pull request merged**
