### PR TITLE
bug : fixing event date

### LINKED ISSUE #99: bug : [ For Upcoming Events It is showing Expired ]
**Describe the bug**
On Event page, for Upcoming Events , the button text is expired, only for present day like if i create an Event on 23/05/2024 and timing is 9:00PM then it will show expired 

**To Reproduce**

1. Go to 'Home'
2. Click on 'Events'
3. Scroll down on 'Events page'

**Expected behavior**
For upcoming Events it should display Register.

**Screenshots**
image
.

**Additional context**
I would like to work on this project to solve this error kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by Yogesh-ok55**
**What kind of change does this PR introduce?**
initially it was comparing only dates not time so, it was creating ambiguity for buttons to show either expired or register so in this PR i have also compared the time along with date , for that i formatted date and time combined in single variable and kept according to new Date() format to compare with it 

**Issue Number:**

Fixes #99 
**Snapshots/Videos:**
lupo-skill

**Other information**

### CODE REVIEW

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55 Update your branch, it has been outdated.

This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`

To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.

You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.

image

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

**Comment by Yogesh-ok55** [comment]
Done..

**Comment by Tanay-ErrorCode** [comment]
> Done..

@Yogesh-ok55 Not main branch but `bug/event-date-fixed`

image

**Review by Doraemon012 — APPROVED** [review]
LGTM

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55 good work.

**Comment by Yogesh-ok55** [comment]
> > Done..
> 
> @Yogesh-ok55 Not main branch but the `bug/event-date-fixed` branch.
> 
> image

Please guide me what to do I am not able to understand

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55 There is no need of this now, as i've already merged the PR.

**Comment by Yogesh-ok55** [comment]
Please mark this issue under gssoc'24 contribution

**Pull request merged**
